### ISSUE TITLE
Help! The new steam update means that the folder is in Steam/steamapps/common/tf2

### ISSUE THREAD

**Issue by alexgaoo** [timstokman/YetAnotherTF2ConfigGenerator#2]
I cant get my configs onto TF2 since THere is the Steampipe update. There is no option for my current account on the config generator

**Comment by timstokman** [comment]
Install the latest version and you should be fine. A few weeks ago I
patched the program to fix the steam pipe issue.
Op 22 mei 2013 04:59 schreef "Nerd645" notifications@github.com het
volgende:

**Comment by timstokman** [comment]
Also, ever since the steam pipe update, you can't install scripts for a
single user, you have to install them for all users. That means the account
option has been removed from the program since it doesn't make sense
combined with steam pipe.
Op 22 mei 2013 04:59 schreef "Nerd645" notifications@github.com het
volgende:
